name: Build .NET Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore Shinystrap.sln

    - name: Build
      run: dotnet build Shinystrap.sln --configuration ${{ matrix.configuration }} --no-restore

    - name: Publish
      run: dotnet publish Shinystrap.sln -c ${{ matrix.configuration }} -o publish-${{ matrix.configuration }}

    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: Shinystrap-${{ matrix.configuration }}
        path: publish-${{ matrix.configuration }}
